### PR TITLE
Fix request independence problems

### LINKED ISSUE #4: Usage example is wrong
Running the client repeatedly using the example only returns the correct result the first time. The reason for that is that each request adds a new method to `@path_steps`. Try for example this:

``` ruby
configuration = CartoDB::Api::Configuration.new
configuration.api_key = '...'
configuration.account = '...'
CartoDB::Api.default_configuration = configuration
cartodb = CartoDB::Api::Request.new(configuration)
cartodb.sql.retrieve params: {q: "SELECT * FROM foo"}
cartodb.sql.retrieve params: {q: "SELECT * FROM bar"}
```

You will get a config like so:

```
=> #<CartoDB::Api::Request:0x007fe1bd35c0e0
 @configuration=
  #<CartoDB::Api::Configuration:0x007fe1c05e7fa0
   @account="...",
   @api_key="...">,
 @path_steps=[:sql, :sql, :sql, :sql, :sql, :sql]>
```

I think it should be clear in the documentation that the user should work on the client returned by the `cartodb.<method>` object.

### LINKED ISSUE #5: Error message body is not displayed
Given a url like this 

```
http://swc28.cartodb.com/api/v2/sql?q=SELECT%20*FROM%20bid2
```

It would be great to be able to see the error message on the console. 

```
{"error":["relation \"bid2\" does not exist"]}
```

Currently all I see is this:

```
CartoDB::Api::Error: the server responded with status 400
```

### PR DESCRIPTION
**Pull request by pablo-co**
#### What's this PR do?

It fixes a bug related to using a `Request` object for multiple requests. It also improves the error messages given by `ApiError`.
#### How should this be manually tested?

Taken from Issue #4
Assuming you have already created and set a default configuration:

``` ruby
cartodb = CartoDB::Api::Request.new
cartodb.sql.retrieve params: {q: "SELECT * FROM foo"}
```
#### What are the relevant tickets?

Fixes #4 regarding the multiple requests 
 Fixes #5 regarding clearer error messages

### CODE REVIEW

File: lib/cartodb/api/request.rb [hunk 1]
```diff
@@ -37,17 +39,32 @@ def update(params: nil, headers: nil, body: nil, payload: nil)
...
+      attr_accessor :configuration
+
+      attr_accessor :path_steps
+
+      def reset_path
+        self.path_steps = []
+      end
+
+      def build_path
+        @path = path_steps.join('/')
```
Comment (pablo-co) [inline lib/cartodb/api/request.rb:62]: Shut up dog.
